name: CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  build:
    name: Build on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, ubuntu-latest-arm]
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application (x64)
      if: matrix.os != 'ubuntu-latest-arm'
      run: npm run build
      env:
        CI: true
        CSC_IDENTITY_AUTO_DISCOVERY: false

    - name: Build application (ARM64)
      if: matrix.os == 'ubuntu-latest-arm'
      run: npm run build -- --arch=arm64
      env:
        CI: true
        CSC_IDENTITY_AUTO_DISCOVERY: false

    - name: Upload build artifacts (Windows)
      if: matrix.os == 'windows-latest' && matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: prism-windows-build
        path: dist/*.exe
        retention-days: 7

    - name: Upload build artifacts (Linux x64)
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: prism-linux-build
        path: |
          dist/*.AppImage
          dist/*.deb
        retention-days: 7

    - name: Upload build artifacts (Linux ARM64)
      if: matrix.os == 'ubuntu-latest-arm' && matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: prism-arm-build
        path: dist/*.AppImage
        retention-days: 7
