name: Release Build

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., v0.1.0)'
        required: false

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Windows x64
      run: npm run build
      env:
        CI: true
        CSC_IDENTITY_AUTO_DISCOVERY: false

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: prism-windows-installer
        path: |
          dist/*.exe
          dist/*.zip
        retention-days: 30

    - name: Upload to GitHub Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.exe
          dist/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    name: Build Linux ${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Set up QEMU for ARM64
      if: matrix.arch == 'arm64'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Install dependencies
      run: npm ci

    - name: Build Linux ${{ matrix.arch }}
      run: |
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          npx electron-builder --linux --arm64
        else
          npx electron-builder --linux --x64
        fi
      env:
        CI: true
        CSC_IDENTITY_AUTO_DISCOVERY: false

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: prism-linux-${{ matrix.arch }}
        path: |
          dist/*.AppImage
          dist/*.deb
        retention-days: 30

    - name: Upload to GitHub Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.AppImage
          dist/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
